### ISSUE TITLE
Change plugin name to "Statify – Extended Evaluation"

### ISSUE THREAD

**Issue by ghost** [patrickrobrecht/extended-evaluation-for-statify#12]
Just a little consideration: What about changing the plugin name to _Statify – Extended Evaluation_ or _Statify: Extended Evaluation_ so it appears in the near of Statify and other Statify extenions in the plugin overview in the backend?

**Comment by patrickrobrecht** [comment]
I'll consider your suggestion for the next release, but I have to check for legal issues before as there was a legal reason for the name _Extended evaluation for Statify_ instead of _Statify: Extended Evaluation_: [The wordpress.org rules](https://developer.wordpress.org/plugins/wordpress-org/plugin-developer-faq/) say: "Similarly you cannot begin the slug of your plugin with someone else’s trademarked term." I'll check that again (there are already other [plugins whose name starts with Statify](https://wordpress.org/plugins/search.php?q=statify)).

**Comment by patrickrobrecht** [comment]
The plugin name has changed with https://github.com/patrickrobrecht/extended-evaluation-for-statify/commit/69fe8bf9cc173521a1ee63602caabbdd5692354b.
